"use client"

import { motion } from "framer-motion"
import { Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Switch } from "@/components/ui/switch"
import { Label } from "@/components/ui/label"
import { Flame, RefreshCw, MessageSquare } from "lucide-react"
import { useState } from "react"

interface RoastSectionProps {
  roast: string
  challenge: string
}

export function RoastSection({ roast, challenge }: RoastSectionProps) {
  const [isPG13, setIsPG13] = useState(false)
  const [isGenerating, setIsGenerating] = useState(false)

  const handleRegenerate = () => {
    setIsGenerating(true)
    setTimeout(() => setIsGenerating(false), 2000)
  }

  return (
    <Card className="glass p-6 border-destructive/30">
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-2">
          <Flame className="w-6 h-6 text-destructive" />
          <h2 className="text-2xl font-bold">Roast Mode</h2>
        </div>
        <div className="flex items-center gap-4">
          <div className="flex items-center gap-2">
            <Switch id="roast-mode" checked={isPG13} onCheckedChange={setIsPG13} />
            <Label htmlFor="roast-mode" className="text-sm cursor-pointer">
              PG-13
            </Label>
          </div>
          <Button
            variant="outline"
            size="sm"
            onClick={handleRegenerate}
            disabled={isGenerating}
            className="bg-transparent"
          >
            <RefreshCw className={`w-4 h-4 mr-2 ${isGenerating ? "animate-spin" : ""}`} />
            Regenerate
          </Button>
        </div>
      </div>

      <motion.div
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ duration: 0.5 }}
        className="space-y-4"
      >
        <div className="glass-strong rounded-lg p-6 border-l-4 border-l-destructive">
          <div className="flex items-start gap-3">
            <MessageSquare className="w-5 h-5 text-destructive mt-1 flex-shrink-0" />
            <div className="space-y-3">
              <p className="text-lg leading-relaxed">{roast}</p>
              <div className="pt-3 border-t border-border/50">
                <p className="text-sm text-muted-foreground mb-2">Challenge for next week:</p>
                <p className="text-sm font-medium text-primary">{challenge}</p>
              </div>
            </div>
          </div>
        </div>

        <p className="text-xs text-muted-foreground text-center">
          Roasts are generated by AI and meant to be playful. Don't take them too seriously!
        </p>
      </motion.div>
    </Card>
  )
}
